import { writeFile, mkdir } from 'fs/promises';
import YAML from 'yaml';
import { join } from 'path';
import { defineBuiltinPlugin } from '../lib/plugins';

interface GithubActionsWorkflowStepOptions {
  id?: string;
  if?: string;
  name?: string;
  uses?: string;
  with?: Record<string, any>;
  run?: string;
  env?: Record<string, string>;
}

interface GithubActionsJobOptions {
  name?: string;
  'timeout-minutes'?: number;
  'runs-on': string;
  env?: Record<string, string>;
  steps: GithubActionsWorkflowStepOptions[];
}

interface GithubActionsWorkflowOptions {
  name?: string;
  on: string[] | Record<string, any>;
  jobs: Record<string, GithubActionsJobOptions>;
}

interface GithubActionsPluginOptions {
  workflows?: Record<string, GithubActionsWorkflowOptions>;
}

export const defaultOptions = {
  workflows: {
    ci: {
      name: 'CI',
      on: {
        push: { branches: ['main'] },
        pull_request: { branches: ['main'] },
      },
      jobs: {
        build: {
          name: 'Code Quality',
          'timeout-minutes': 15,
          'runs-on': 'ubuntu-latest',
          env: {
            DO_NOT_TRACK: '1',
          },
          steps: [
            {
              id: 'checkout',
              name: 'Check out code',
              uses: 'actions/checkout@v4',
              with: {
                'fetch-depth': 2,
                lfs: true,
              },
            },
            {
              id: 'setup-node',
              name: 'Setup Node.js environment',
              uses: 'actions/setup-node@v4',
              with: {
                'node-version': 22,
              },
            },
            {
              id: 'install',
              name: 'Install dependencies',
              // NOTE: run is set by e.g. pnpm plugin
            },
            {
              id: 'checks',
              name: 'Code Quality Checks',
              run: 'pnpm turbo check lint test build',
            },
            {
              id: 'ensure-clean',
              name: 'Ensure there are no uncommitted changes',
              run: 'git diff --exit-code || (echo "There are uncommitted changes!" && exit 1)',
            },
            {
              // TODO: Move to @toolsync/builtin/changesets plugin
              id: 'changesets',
              // if the event is a push this also implies that the branch is main
              if: "${{ github.event_name == 'push' }}",
              name: 'Changesets',
              uses: 'changesets/action@v1',
              with: {
                commit: 'chore: Update versions',
                title: 'chore: Update versions',
                publish: 'pnpm changeset publish',
                commitMode: 'github-api',
              },
              env: {
                GITHUB_TOKEN: '${{ secrets.CHANGESETS_GITHUB_TOKEN }}',
                NPM_TOKEN: '${{ secrets.NPM_TOKEN }}',
              },
            },
          ],
        },
      },
    },
  },
} satisfies GithubActionsPluginOptions;

export const githubActionsPluginName = '@toolsync/builtin/github-actions';

declare global {
  namespace Toolsync {
    interface ConfigMap {
      [githubActionsPluginName]: GithubActionsPluginOptions;
    }
  }
}

const githubActionsPlugin = defineBuiltinPlugin({
  name: githubActionsPluginName,
  description: 'Integrates with GitHub Actions for CI workflows',
  loadConfig: () => ({
    config: {
      [githubActionsPluginName]: defaultOptions,
      '@toolsync/builtin/vscode': {
        extensions: {
          recommendations: ['github.vscode-github-actions'],
        },
      },
    },
  }),
  async setupPackage(pkg, { log, options }) {
    if (pkg.isRoot) {
      for (const [name, workflow] of Object.entries(options.workflows || {})) {
        const dir = join(pkg.dir, '.github', 'workflows');

        const doc = new YAML.Document(workflow);
        doc.commentBefore = [
          `Generated by ${githubActionsPluginName}`,
          `Do not edit manually, instead update your toolsync config and run \`toolsync prepare\``,
          'See: https://toolsync.vercel.app/docs/configuration',
        ]
          .map((line) => ` ${line}`)
          .join('\n');

        await mkdir(dir, { recursive: true });
        // TODO: Update if file already exists
        await writeFile(
          join(dir, `${name}.yml`),
          YAML.stringify(doc, {
            // TODO: Get from prettier settings
            singleQuote: true,
          }),
        );
      }
    }
  },
});

export default githubActionsPlugin;
