import { definePlugin, type Plugin } from '@toolsync/core/plugins';
import { join } from 'path';
import { name, homepage } from '../package.json';
import { MarkdownTemplate } from '@toolsync/template';

const repoPlugin = definePlugin({
  name,
  loadConfig() {
    return {
      config: {
        '@toolsync/builtin/github-actions': {
          workflows: {
            ci: {
              jobs: {
                build: {
                  steps: [
                    {
                      '@insert': {
                        before: 'install',
                        data: {
                          name: 'Prepare toolsync',
                          run: `pnpm install --ignore-scripts && pnpm build`,
                        },
                      },
                    },
                  ],
                },
              },
            },
          },
        },
      },
    };
  },
  async setupPackage(pkg, {}) {
    if (pkg.packageJson.name === '@toolsync/builtin') {
      const { exports: exportedTools } = pkg.packageJson;

      const tools: Plugin[] = [];

      for (const importPath of Object.keys(exportedTools!)) {
        if (importPath === '.') continue; // Skip the root export

        const importReference = join('@toolsync/builtin', importPath);
        const { default: plugin } = (await import(importReference)) as { default: Plugin };

        tools.push(plugin);
      }

      const readme = await MarkdownTemplate.load(join(pkg.dir, 'README.md'), {
        notice: `Generated by ${name}. Do not edit manually, instead run \`toolsync prepare\`.`,
      });

      readme.update({
        section: 'tools',
        insert: 'bottom',
        content: `## Tools

${tools.map((tool) => `- ${[`**${tool.name}**`, ...(tool.description ? [tool.description] : [])].join(' - ')}`).join('\n')}
`,
      });

      await readme.save();
    }

    if (!pkg.isRoot) {
      const readme = await MarkdownTemplate.load(join(pkg.dir, 'README.md'), {
        notice: `Generated by ${name}. Do not edit manually, instead run \`toolsync prepare\`.`,
      });

      readme.update({
        section: 'footer',
        insert: 'bottom',
        content: `---

Part of the [toolsync](${homepage}) project.
`,
      });

      await readme.save();
    }
  },
});

export default repoPlugin;
