import { definePlugin } from '@toolsync/core/plugins';
import { join } from 'path';
import { name, homepage } from '../package.json';
import { MarkdownTemplate } from '@toolsync/template';

declare global {
  namespace Toolsync {
    interface ConfigMap {
      [name]: {};
    }
  }
}

const repoPlugin = definePlugin({
  name,
  loadConfig() {
    return {
      config: {
        '@toolsync/builtin/github-actions': {
          workflows: {
            ci: {
              jobs: {
                build: {
                  // TODO: Move to turborepo toolsync plugin
                  env: {
                    TURBO_TEAM: '${{ vars.TURBO_TEAM }}',
                    TURBO_TOKEN: '${{ secrets.TURBO_TOKEN }}',
                  },
                  steps: [
                    {
                      '@insert': {
                        before: 'install',
                        data: {
                          name: 'Prepare toolsync',
                          run: `pnpm install --ignore-scripts && pnpm build`,
                        },
                      },
                    },
                  ],
                },
              },
            },
          },
        },
      },
    };
  },
  async setupPackage(pkg, {}) {
    if (!pkg.isRoot) {
      const readme = await MarkdownTemplate.load(join(pkg.dir, 'README.md'), {
        notice: `Generated by ${name}. Do not edit manually, instead run \`toolsync prepare\`.`,
      });

      readme.update({
        section: 'footer',
        insert: 'bottom',
        content: `---

Part of the [toolsync](${homepage}) project.
`,
      });

      await readme.save();
    }
  },
});

export default repoPlugin;
