import { definePlugin, type Plugin } from '@toolsync/core/plugins';
import { join } from 'path';
import { name } from '../package.json';
import { MarkdownTemplate } from '@toolsync/builtin/package-readme';

const repoPlugin = definePlugin({
  name,
  async setupPackage(pkg, {}) {
    if (pkg.packageJson.name === '@toolsync/builtin') {
      const { exports: exportedTools } = pkg.packageJson;

      const tools: Plugin[] = [];

      for (const importPath of Object.keys(exportedTools!)) {
        if (importPath === '.') continue; // Skip the root export

        const importReference = join('@toolsync/builtin', importPath);
        const { default: plugin } = (await import(importReference)) as { default: Plugin };

        tools.push(plugin);
      }

      const readme = await MarkdownTemplate.load(join(pkg.dir, 'README.md'), {
        notice: `Generated by ${name}. Do not edit manually, instead run \`toolsync prepare\`.`,
      });

      readme.update({
        section: 'tools',
        insert: 'bottom',
        content: `## Tools

${tools.map((tool) => `- ${[`**${tool.name}**`, ...(tool.description ? [tool.description] : [])].join(' - ')}`).join('\n')}
`,
      });

      await readme.save();
    }
  },
});

export default repoPlugin;
